In [226]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# Load Titanic dataset
titanic = sns.load_dataset('titanic')

# Export to CSV
titanic.to_csv('titanic.csv', index=False)

print(titanic.head(10))

   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third
1         1       1  female  38.0      1      0  71.2833        C   First
2         1       3  female  26.0      0      0   7.9250        S   Third
3         1       1  female  35.0      1      0  53.1000        S   First
4         0       3    male  35.0      0      0   8.0500        S   Third
5         0       3    male   NaN      0      0   8.4583        Q   Third
6         0       1    male  54.0      0      0  51.8625        S   First
7         0       3    male   2.0      3      1  21.0750        S   Third
8         1       3  female  27.0      0      2  11.1333        S   Third
9         1       2  female  14.0      1      0  30.0708        C  Second

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
5    man        True  NaN   Queenstown    no   True
6    man        True    E  Southampton    no   True
7  child       False  NaN  Southampton    no  False
8  woman       False  NaN  Southampton   yes  False
9  child       False  NaN    Cherbourg   yes  False

In [227]:
print(titanic.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [228]:
print(titanic.duplicated().sum())
titanic = titanic.drop_duplicates()
print(titanic.duplicated().sum())

107
0

In [229]:
titanic['age'] = titanic['age'].fillna(titanic['age'].mean())

In [230]:
print(titanic.isnull().sum())

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           582
embark_town      2
alive            0
alone            0
dtype: int64

In [231]:
titanic.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [232]:
titanic['deck'] = titanic['deck'].cat.add_categories('unknown')
titanic['deck'] = titanic['deck'].fillna('unknown')
titanic['embark_town'] = titanic['embark_town'].fillna('0')
titanic['embarked'] = titanic['embarked'].fillna('0')
print(titanic.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [233]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,unknown,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,unknown,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,unknown,Southampton,no,True

In [234]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
catcols= ['sex','who','adult_male','embark_town','alive','alone','class','embarked']
for col in catcols:
    titanic[col] = le.fit_transform(titanic[col])
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.000000,1,0,7.2500,3,2,1,1,unknown,3,0,0
1,1,1,0,38.000000,1,0,71.2833,1,0,2,0,C,1,1,0
2,1,3,0,26.000000,0,0,7.9250,3,2,2,0,unknown,3,1,1
3,1,1,0,35.000000,1,0,53.1000,3,0,2,0,C,3,1,0
4,0,3,1,35.000000,0,0,8.0500,3,2,1,1,unknown,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,0,39.000000,0,5,29.1250,2,2,2,0,unknown,2,0,0
887,1,1,0,19.000000,0,0,30.0000,3,0,2,0,B,3,1,1
888,0,3,0,29.869351,1,2,23.4500,3,2,2,0,unknown,3,0,0
889,1,1,1,26.000000,0,0,30.0000,1,0,1,1,C,1,1,1
890,0,3,1,32.000000,0,0,7.7500,2,2,1,1,unknown,2,0,1

In [235]:
features = []

In [236]:
# from sklearn.preprocessing import StandardScaler
# std = StandardScaler()

# titanic[['pclass', 'age', 'fare']] = std.fit_transform(
#     titanic[['pclass', 'age', 'fare']]
# )

# titanic.head()

In [237]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.000000,1,0,7.2500,3,2,1,1,unknown,3,0,0
1,1,1,0,38.000000,1,0,71.2833,1,0,2,0,C,1,1,0
2,1,3,0,26.000000,0,0,7.9250,3,2,2,0,unknown,3,1,1
3,1,1,0,35.000000,1,0,53.1000,3,0,2,0,C,3,1,0
4,0,3,1,35.000000,0,0,8.0500,3,2,1,1,unknown,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,0,39.000000,0,5,29.1250,2,2,2,0,unknown,2,0,0
887,1,1,0,19.000000,0,0,30.0000,3,0,2,0,B,3,1,1
888,0,3,0,29.869351,1,2,23.4500,3,2,2,0,unknown,3,0,0
889,1,1,1,26.000000,0,0,30.0000,1,0,1,1,C,1,1,1
890,0,3,1,32.000000,0,0,7.7500,2,2,1,1,unknown,2,0,1

In [238]:
features = ['pclass', 'sex', 'age', 'sibsp', 'parch',
            'fare', 'embarked', 'class', 'who',
            'adult_male', 'alone']

X = titanic[features]
y = titanic['survived']

In [239]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(627, 11)
(157, 11)

In [240]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.7388535031847133